version: 2
jobs:
  build:
    docker:
      - image: circleci/Android:target-25
    steps:
      - checkout
      - run: ./gradlew clean build
  test:
    docker:
      - image: circleci/android:target-25
    steps:
      - checkout
      - run: ./gradlew clean build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
